// @ts-nocheck
// Hera's reminders (Supabase Edge Function "hera-nudge").
// Built from backend/hera-nudge.template.ts. Do not edit this file directly.
// Paste the generated backend/hera-nudge.ts into Supabase → Edge Functions → hera-nudge (Verify JWT off).
//
// Three jobs:
//   {action:"run"}         every 15 minutes from Supabase Cron (needs the x-cron-secret header)
//   {action:"public_key"}  the app asks for the key it needs to subscribe to notifications
//   {action:"test"}        a signed-in woman asks for a test notification

import { createClient } from 'npm:@supabase/supabase-js@2'
import webpush from 'npm:web-push@3.6.7'

// ---- copied from src/lib/cycle.js ----

const DAY_MS = 86400000

function toDays(iso) {
  const [y, m, d] = iso.split('-').map(Number)
  return Date.UTC(y, m - 1, d) / DAY_MS
}

function fromDays(n) {
  return new Date(n * DAY_MS).toISOString().slice(0, 10)
}

function addDays(iso, n) {
  return fromDays(toDays(iso) + n)
}

function daysBetween(a, b) {
  return toDays(b) - toDays(a)
}

const WEEKDAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

function prettyDate(iso) {
  const n = toDays(iso)
  const d = new Date(n * DAY_MS)
  return `${WEEKDAYS[d.getUTCDay()]} ${d.getUTCDate()} ${MONTHS[d.getUTCMonth()]}`
}

const NO_PHASE_CONTRACEPTION = {
  combined: 'the combined pill, patch or ring',
  progestin_pill: 'the mini-pill',
  hormonal_iud: 'a hormonal IUD',
  implant: 'an implant or injection'
}

const PHASE_LABELS = {
  menstrual: 'Menstrual phase',
  follicular: 'Follicular phase',
  ovulatory: 'Ovulatory phase',
  luteal: 'Luteal phase'
}

/**
 * @param profile  row from public.profiles
 * @param starts   period start dates ('YYYY-MM-DD'), any order
 * @param today    'YYYY-MM-DD'
 */
function computeCycle(profile = {}, starts = [], today) {
  const stage = profile.life_stage || 'cycles'
  const conditions = profile.conditions || []

  if (stage === 'pregnant') return { mode: 'pregnant' }
  if (stage === 'postmenopause') return { mode: 'menopause' }
  if (NO_PHASE_CONTRACEPTION[profile.contraception]) {
    return { mode: 'no_phases', reason: NO_PHASE_CONTRACEPTION[profile.contraception] }
  }

  const all = [...new Set([...starts, profile.last_period_start].filter(Boolean))]
    .filter(d => toDays(d) <= toDays(today))
    .sort()
  if (all.length === 0) return { mode: 'unknown' }

  const lastStart = all[all.length - 1]

  // Cycle lengths from her own history (ignore gaps that can't be one cycle).
  const gaps = []
  for (let i = 1; i < all.length; i++) {
    const g = daysBetween(all[i - 1], all[i])
    if (g >= 15 && g <= 90) gaps.push(g)
  }
  const recent = gaps.slice(-6)
  const fromHistory = recent.length >= 2
  const cycleLength = fromHistory
    ? Math.round(recent.reduce((a, b) => a + b, 0) / recent.length)
    : (profile.cycle_length || 28)
  const periodLength = profile.period_length || 5

  const irregular = recent.length >= 2 && Math.max(...recent) - Math.min(...recent) > 7
  const pcos = conditions.some(c => /pcos|pcod/i.test(c))
  const rough = irregular || pcos || stage === 'perimenopause' ||
    (!fromHistory && !profile.cycle_length_known)
  const spread = rough ? 5 : fromHistory ? 2 : 3

  const day = daysBetween(lastStart, today) + 1
  const ovDay = Math.max(cycleLength - 14, periodLength + 1)
  const expected = addDays(lastStart, cycleLength)
  const ovulation = addDays(lastStart, ovDay - 1)

  const result = {
    mode: 'cycle',
    lastStart,
    day,
    cycleLength,
    periodLength,
    rough,
    irregular,
    pcos,
    basedOn: fromHistory ? `${recent.length + 1} logged periods` : 'what you told me at signup',
    nextPeriod: { from: addDays(expected, -spread), to: addDays(expected, spread), expected },
    ovulation,
    fertileWindow: { from: addDays(ovulation, -5), to: ovulation },
    phase: null,
    lateLuteal: false,
    lateBy: 0
  }

  if (day > cycleLength + spread) {
    result.phase = 'late'
    result.lateBy = day - cycleLength
    return result
  }

  if (day <= periodLength) result.phase = 'menstrual'
  else if (day < ovDay - 1) result.phase = 'follicular'
  else if (day <= ovDay + 1) result.phase = 'ovulatory'
  else result.phase = 'luteal'

  result.lateLuteal = result.phase === 'luteal' && day > cycleLength - 7
  return result
}

function describeCycle(c) {
  switch (c.mode) {
    case 'pregnant':
      return 'She is pregnant. Do not predict periods or phases.'
    case 'menopause':
      return 'She is postmenopausal. No cycle predictions. Any vaginal bleeding now is a red flag for a doctor visit.'
    case 'no_phases':
      return `She uses ${c.reason}, so she has no natural cycle phases. Do not predict phases, ovulation or a fertile window. Track bleeding and symptoms only.`
    case 'unknown':
      return 'No period date logged yet. If relevant, gently ask when her last period started.'
  }
  const parts = [
    `Last period started ${prettyDate(c.lastStart)} (cycle day ${c.day}).`,
    `Typical cycle about ${c.cycleLength} days, based on ${c.basedOn}.`
  ]
  if (c.phase === 'late') {
    parts.push(`Her period is about ${c.lateBy} days later than expected. Don't alarm her; suggest a pregnancy test if that's possible for her, and a doctor if she's often late or it's been over 3 months.`)
  } else {
    parts.push(`Current phase: ${c.phase}${c.lateLuteal ? ' (late luteal: the PMS days, mood often lowest)' : ''}.`)
    parts.push(`Next period expected between ${prettyDate(c.nextPeriod.from)} and ${prettyDate(c.nextPeriod.to)}.`)
    parts.push(`Estimated fertile window ${prettyDate(c.fertileWindow.from)} to ${prettyDate(c.fertileWindow.to)} (an estimate, never contraception).`)
  }
  if (c.rough) {
    parts.push(`Predictions are rough${c.pcos ? ' because of PCOS/PCOD' : c.irregular ? ' because her cycles vary' : ''}; say so if you give dates.`)
  }
  return parts.join(' ')
}

// ---- copied from src/lib/nudges.js ----

const DAILY_CAP = 3
const WEEKDAY_NAMES = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']

function localClock(now, timeZone) {
  let parts
  try {
    parts = new Intl.DateTimeFormat('en-GB', {
      timeZone, year: 'numeric', month: '2-digit', day: '2-digit',
      hour: '2-digit', minute: '2-digit', weekday: 'short', hourCycle: 'h23'
    }).formatToParts(now)
  } catch {
    return localClock(now, 'Asia/Kolkata')
  }
  const get = t => parts.find(p => p.type === t)?.value
  const wd = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].indexOf(get('weekday'))
  return { date: `${get('year')}-${get('month')}-${get('day')}`, minutes: Number(get('hour')) * 60 + Number(get('minute')), weekday: wd }
}

function toMinutes(hhmm, fallback) {
  const m = /^(\d{1,2}):(\d{2})/.exec(hhmm || '')
  return m ? Number(m[1]) * 60 + Number(m[2]) : fallback
}

function inQuietHours(minutes, start, end) {
  if (start === end) return false
  return start < end ? minutes >= start && minutes < end : minutes >= start || minutes < end
}

/**
 * Decide the one nudge to send now, or null.
 * @param p        profile row (with reminder settings)
 * @param starts   period start dates
 * @param ends     period end dates
 * @param sent     [{kind, for_date}] already sent recently
 * @param now      Date
 */
function dueNudge(p, starts, ends, sent, now) {
  const clock = localClock(now, p.timezone || 'Asia/Kolkata')
  const today = clock.date
  if (p.paused_until && new Date(p.paused_until) > now) return null
  if (inQuietHours(clock.minutes, toMinutes(p.quiet_start, 22 * 60), toMinutes(p.quiet_end, 8 * 60))) return null
  if (clock.minutes < toMinutes(p.nudge_time, 9 * 60)) return null

  const sentToday = sent.filter(s => s.for_date === today)
  if (sentToday.length >= DAILY_CAP) return null
  const already = kind => sentToday.some(s => s.kind === kind)

  const cycle = computeCycle(p, starts, today)
  const candidates = []

  if (cycle.mode === 'cycle') {
    const toExpected = daysBetween(today, cycle.nextPeriod.expected)
    const pastExpected = -toExpected
    if (pastExpected === 0 || pastExpected === 2) candidates.push('period_check')
    if (toExpected === 2) candidates.push('period_heads_up')
    const endedSinceStart = ends.some(e => e >= cycle.lastStart)
    if (cycle.day === 4 && !endedSinceStart) candidates.push('period_end_check')
  }
  if (clock.weekday === (p.checkin_day ?? 0)) candidates.push('weekly_checkin')
  if (p.daily_tips) candidates.push('daily_tip')

  const kind = candidates.find(k => !already(k))
  if (!kind) return null
  return { kind, for_date: today, text: nudgeText(kind, p, cycle, today) }
}


const PHASE_WORDS = {
  menstrual: 'your period days', follicular: 'your follicular phase', ovulatory: 'your ovulation days',
  luteal: 'your luteal phase', late: 'this stretch'
}

const TIPS = {
  menstrual: [
    'Iron + vitamin C today: palak or rajma with a squeeze of lemon. And keep warm water or ginger tea close 💜',
    'Aim for 2.5–3 L of water today. Warm fluids and a hot water bag help with cramps.',
    'Gentle is the goal today: a short walk or easy stretches beat a hard workout.'
  ],
  follicular: [
    'Energy is rising! A great week to try that workout or start something new.',
    'Fresh and light works well now: sprouts, curd, idli or a millet bowl.',
    'About 2–2.5 L of water is enough this week, more if you work out.'
  ],
  ovulatory: [
    'Peak energy days: perfect for plans, presentations or a big workout.',
    'Load up on fibre and colour: cabbage, papaya, fruits, nuts and seeds.',
    'Your body runs a little warmer now. Keep about 2.5 L of water going.'
  ],
  luteal: [
    'Cravings? Go for complex carbs like ragi, oats or sweet potato to keep your mood steady.',
    'Magnesium helps with PMS: bananas, pumpkin seeds, chickpeas, leafy greens.',
    'Go easy on salt and caffeine this week. 2.5–3 L of water actually reduces bloating.'
  ]
}

function nudgeText(kind, p, cycle, today = '2026-01-01') {
  const tone = p.tone || 'bestie'
  const name = p.name ? p.name.split(' ')[0] : ''
  const hi = tone === 'bestie' ? `Hey ${name || 'babe'}! ` : tone === 'gentle' ? `Hi${name ? ` ${name}` : ''}. ` : ''
  const heart = tone === 'facts' ? '' : ' 💜'

  switch (kind) {
    case 'period_heads_up':
      return tone === 'facts'
        ? 'Your period is expected in about 2 days. Keep pads or a cup handy.'
        : `${hi}Your period might show up in the next couple of days. Keep your pads or cup handy and go easy on yourself${heart}`
    case 'period_check':
      return tone === 'facts'
        ? 'Did your period start? Reply "started today" or "not yet".'
        : `${hi}Did your period start? Just reply "started today" or "not yet" and I'll handle the rest${heart}`
    case 'period_end_check':
      return tone === 'facts'
        ? 'Day 4 of your period. Is it over, or still going?'
        : `${hi}It's day 4 of your period. Is it over, or still going?`
    case 'weekly_checkin': {
      const where = PHASE_WORDS[cycle.phase] ?? 'this week'
      const q = cycle.lateLuteal
        ? '1) Any bloating, cramps or headaches? 2) How\'s your mood, honestly? PMS days can feel heavy. 3) How are you sleeping?'
        : '1) How\'s your body feeling? 2) How\'s your mood? 3) How are you sleeping?'
      const lead = cycle.mode === 'cycle' ? `Weekly check-in for ${where}.` : 'Weekly check-in.'
      return tone === 'facts' ? `${lead} ${q}` : `${hi}${lead} ${q} Answer whatever you like${heart}`
    }
    case 'daily_tip': {
      const list = TIPS[cycle.phase] ?? ['Drink some water, stretch for a minute, and check in with how you feel today.']
      const pick = list[Math.abs(daysBetween('2026-01-01', today)) % list.length]
      return tone === 'facts' ? pick.replace(/ 💜|!/g, '.').replace(/\.\./g, '.') : `${hi}${pick}`
    }
  }
  return ''
}



const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, x-cron-secret',
  'Access-Control-Allow-Methods': 'POST, OPTIONS'
}
const APP_URL = 'https://hera-ecru.vercel.app'

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), { status, headers: { ...CORS, 'Content-Type': 'application/json' } })
}

// Server key: the new secret key if present, else the legacy service role key.
function serverKey() {
  try {
    const keys = JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS') ?? '{}')
    const first = Object.values(keys)[0]
    if (first) return String(first)
  } catch { /* not set */ }
  return Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
}

const admin = createClient(Deno.env.get('SUPABASE_URL')!, serverKey(), { auth: { persistSession: false } })

async function setting(key: string) {
  const { data } = await admin.from('hera_settings').select('value').eq('key', key).maybeSingle()
  return data?.value as string | undefined
}

// Notification keys are created once, on first use, and kept in hera_settings.
async function vapidKeys() {
  let pub = await setting('vapid_public'), priv = await setting('vapid_private')
  if (!pub || !priv) {
    const k = webpush.generateVAPIDKeys()
    await admin.from('hera_settings').insert([{ key: 'vapid_public', value: k.publicKey }, { key: 'vapid_private', value: k.privateKey }])
    pub = await setting('vapid_public'); priv = await setting('vapid_private') // another run may have won the race
  }
  return { publicKey: pub!, privateKey: priv! }
}

type Sub = { id: number; user_id: string; endpoint: string; p256dh: string; auth: string }

async function pushTo(sub: Sub, payload: Record<string, string>, keys: { publicKey: string; privateKey: string }) {
  const d = webpush.generateRequestDetails(
    { endpoint: sub.endpoint, keys: { p256dh: sub.p256dh, auth: sub.auth } },
    JSON.stringify(payload),
    { TTL: 24 * 3600, urgency: 'normal', vapidDetails: { subject: APP_URL, ...keys } }
  )
  const headers: Record<string, string> = {}
  for (const [k, v] of Object.entries(d.headers)) headers[k] = String(v)
  const res = await fetch(d.endpoint, { method: 'POST', headers, body: d.body })
  if (res.status === 404 || res.status === 410) {
    await admin.from('push_subscriptions').delete().eq('id', sub.id) // phone unsubscribed or app removed
  }
  return res.ok
}

async function runBatch(now: Date) {
  const keys = await vapidKeys()
  const { data: subs } = await admin.from('push_subscriptions').select('*')
  const byUser = new Map<string, Sub[]>()
  for (const s of (subs ?? []) as Sub[]) byUser.set(s.user_id, [...(byUser.get(s.user_id) ?? []), s])
  const ids = [...byUser.keys()]
  if (!ids.length) return { checked: 0, sent: 0 }

  const utcToday = now.toISOString().slice(0, 10)
  const [{ data: profiles }, { data: logs }, { data: sent }] = await Promise.all([
    admin.from('profiles').select('*').in('id', ids).not('onboarded_at', 'is', null),
    admin.from('cycle_logs').select('user_id, log_date, kind').in('user_id', ids)
      .in('kind', ['period_start', 'period_end']).gte('log_date', addDays(utcToday, -200)),
    admin.from('nudges_sent').select('user_id, kind, for_date').in('user_id', ids).gte('for_date', addDays(utcToday, -3))
  ])

  let count = 0
  for (const p of profiles ?? []) {
    const mine = (logs ?? []).filter((l: { user_id: string }) => l.user_id === p.id)
    const starts = mine.filter((l: { kind: string }) => l.kind === 'period_start').map((l: { log_date: string }) => l.log_date)
    const ends = mine.filter((l: { kind: string }) => l.kind === 'period_end').map((l: { log_date: string }) => l.log_date)
    const already = (sent ?? []).filter((s: { user_id: string }) => s.user_id === p.id)
    const nudge = dueNudge(p, starts, ends, already, now)
    if (!nudge) continue

    // Claim it first: the table's key makes a second run skip the same reminder.
    const { error: claimErr } = await admin.from('nudges_sent').insert({ user_id: p.id, kind: nudge.kind, for_date: nudge.for_date })
    if (claimErr) continue

    await admin.from('messages').insert({ user_id: p.id, role: 'hera', content: nudge.text })
    for (const sub of byUser.get(p.id) ?? []) {
      try {
        await pushTo(sub, { title: 'Hera', body: nudge.text, tag: nudge.kind, url: '/' }, keys)
      } catch (e) {
        console.error('push failed:', String(e))
      }
    }
    count++
  }
  return { checked: (profiles ?? []).length, sent: count }
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: CORS })
  if (req.method !== 'POST') return json({ error: 'Use POST' }, 405)
  try {
    const body = await req.json().catch(() => ({}))

    if (body.action === 'public_key') {
      return json({ publicKey: (await vapidKeys()).publicKey })
    }

    if (body.action === 'test') {
      const user = createClient(Deno.env.get('SUPABASE_URL')!, req.headers.get('apikey') ?? Deno.env.get('SUPABASE_ANON_KEY') ?? '', {
        global: { headers: { Authorization: req.headers.get('Authorization') ?? '' } },
        auth: { persistSession: false }
      })
      const { data } = await user.auth.getUser()
      if (!data?.user) return json({ error: 'not_signed_in' }, 401)
      const keys = await vapidKeys()
      const { data: subs } = await admin.from('push_subscriptions').select('*').eq('user_id', data.user.id)
      let ok = 0
      for (const sub of (subs ?? []) as Sub[]) if (await pushTo(sub, { title: 'Hera', body: "This is how my reminders will look 💜", tag: 'test', url: '/' }, keys)) ok++
      return json({ devices: (subs ?? []).length, delivered: ok })
    }

    if (body.action === 'run') {
      const secret = await setting('cron_secret')
      if (!secret || req.headers.get('x-cron-secret') !== secret) return json({ error: 'forbidden' }, 403)
      const result = await runBatch(new Date())
      console.log('nudge run:', JSON.stringify(result))
      return json(result)
    }

    return json({ error: 'unknown_action' }, 400)
  } catch (e) {
    console.error('hera-nudge failed:', e)
    return json({ error: 'server_error' }, 500)
  }
})
