// @ts-nocheck
// Hera's chat function (Supabase Edge Function "hera-chat").
// Built from backend/hera-chat.template.ts. Do not edit this file directly.
// Paste the generated backend/hera-chat.ts into Supabase → Edge Functions → hera-chat.

import { createClient } from 'npm:@supabase/supabase-js@2'

// ---- Cycle engine (copied from src/lib/cycle.js) ----

const DAY_MS = 86400000

function toDays(iso) {
  const [y, m, d] = iso.split('-').map(Number)
  return Date.UTC(y, m - 1, d) / DAY_MS
}

function fromDays(n) {
  return new Date(n * DAY_MS).toISOString().slice(0, 10)
}

function addDays(iso, n) {
  return fromDays(toDays(iso) + n)
}

function daysBetween(a, b) {
  return toDays(b) - toDays(a)
}

const WEEKDAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

function prettyDate(iso) {
  const n = toDays(iso)
  const d = new Date(n * DAY_MS)
  return `${WEEKDAYS[d.getUTCDay()]} ${d.getUTCDate()} ${MONTHS[d.getUTCMonth()]}`
}

const NO_PHASE_CONTRACEPTION = {
  combined: 'the combined pill, patch or ring',
  progestin_pill: 'the mini-pill',
  hormonal_iud: 'a hormonal IUD',
  implant: 'an implant or injection'
}

const PHASE_LABELS = {
  menstrual: 'Menstrual phase',
  follicular: 'Follicular phase',
  ovulatory: 'Ovulatory phase',
  luteal: 'Luteal phase'
}

/**
 * @param profile  row from public.profiles
 * @param starts   period start dates ('YYYY-MM-DD'), any order
 * @param today    'YYYY-MM-DD'
 */
function computeCycle(profile = {}, starts = [], today) {
  const stage = profile.life_stage || 'cycles'
  const conditions = profile.conditions || []

  if (stage === 'pregnant') return { mode: 'pregnant' }
  if (stage === 'postmenopause') return { mode: 'menopause' }
  if (NO_PHASE_CONTRACEPTION[profile.contraception]) {
    return { mode: 'no_phases', reason: NO_PHASE_CONTRACEPTION[profile.contraception] }
  }

  const all = [...new Set([...starts, profile.last_period_start].filter(Boolean))]
    .filter(d => toDays(d) <= toDays(today))
    .sort()
  if (all.length === 0) return { mode: 'unknown' }

  const lastStart = all[all.length - 1]

  // Cycle lengths from her own history (ignore gaps that can't be one cycle).
  const gaps = []
  for (let i = 1; i < all.length; i++) {
    const g = daysBetween(all[i - 1], all[i])
    if (g >= 15 && g <= 90) gaps.push(g)
  }
  const recent = gaps.slice(-6)
  const fromHistory = recent.length >= 2
  const cycleLength = fromHistory
    ? Math.round(recent.reduce((a, b) => a + b, 0) / recent.length)
    : (profile.cycle_length || 28)
  const periodLength = profile.period_length || 5

  const irregular = recent.length >= 2 && Math.max(...recent) - Math.min(...recent) > 7
  const pcos = conditions.some(c => /pcos|pcod/i.test(c))
  const rough = irregular || pcos || stage === 'perimenopause' ||
    (!fromHistory && !profile.cycle_length_known)
  const spread = rough ? 5 : fromHistory ? 2 : 3

  const day = daysBetween(lastStart, today) + 1
  const ovDay = Math.max(cycleLength - 14, periodLength + 1)
  const expected = addDays(lastStart, cycleLength)
  const ovulation = addDays(lastStart, ovDay - 1)

  const result = {
    mode: 'cycle',
    lastStart,
    day,
    cycleLength,
    periodLength,
    rough,
    irregular,
    pcos,
    basedOn: fromHistory ? `${recent.length + 1} logged periods` : 'what you told me at signup',
    nextPeriod: { from: addDays(expected, -spread), to: addDays(expected, spread), expected },
    ovulation,
    fertileWindow: { from: addDays(ovulation, -5), to: ovulation },
    phase: null,
    lateLuteal: false,
    lateBy: 0
  }

  if (day > cycleLength + spread) {
    result.phase = 'late'
    result.lateBy = day - cycleLength
    return result
  }

  if (day <= periodLength) result.phase = 'menstrual'
  else if (day < ovDay - 1) result.phase = 'follicular'
  else if (day <= ovDay + 1) result.phase = 'ovulatory'
  else result.phase = 'luteal'

  result.lateLuteal = result.phase === 'luteal' && day > cycleLength - 7
  return result
}

function describeCycle(c) {
  switch (c.mode) {
    case 'pregnant':
      return 'She is pregnant. Do not predict periods or phases.'
    case 'menopause':
      return 'She is postmenopausal. No cycle predictions. Any vaginal bleeding now is a red flag for a doctor visit.'
    case 'no_phases':
      return `She uses ${c.reason}, so she has no natural cycle phases. Do not predict phases, ovulation or a fertile window. Track bleeding and symptoms only.`
    case 'unknown':
      return 'No period date logged yet. If relevant, gently ask when her last period started.'
  }
  const parts = [
    `Last period started ${prettyDate(c.lastStart)} (cycle day ${c.day}).`,
    `Typical cycle about ${c.cycleLength} days, based on ${c.basedOn}.`
  ]
  if (c.phase === 'late') {
    parts.push(`Her period is about ${c.lateBy} days later than expected. Don't alarm her; suggest a pregnancy test if that's possible for her, and a doctor if she's often late or it's been over 3 months.`)
  } else {
    parts.push(`Current phase: ${c.phase}${c.lateLuteal ? ' (late luteal: the PMS days, mood often lowest)' : ''}.`)
    parts.push(`Next period expected between ${prettyDate(c.nextPeriod.from)} and ${prettyDate(c.nextPeriod.to)}.`)
    parts.push(`Estimated fertile window ${prettyDate(c.fertileWindow.from)} to ${prettyDate(c.fertileWindow.to)} (an estimate, never contraception).`)
  }
  if (c.rough) {
    parts.push(`Predictions are rough${c.pcos ? ' because of PCOS/PCOD' : c.irregular ? ' because her cycles vary' : ''}; say so if you give dates.`)
  }
  return parts.join(' ')
}


const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS'
}

const LOG_KINDS = ['period_start', 'period_end', 'flow', 'pain', 'mood', 'energy', 'symptom', 'sleep', 'sex_drive', 'note']
const HELPLINE = 'You can call Tele-MANAS on 14416 (free, 24/7) to talk to a counsellor right now, or 112 in an emergency.'

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), { status, headers: { ...CORS, 'Content-Type': 'application/json' } })
}

function todayInIndia() {
  return new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Kolkata' }).format(new Date())
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: CORS })
  if (req.method !== 'POST') return json({ error: 'Use POST' }, 405)

  try {
    // ---- Who is this? (we check the login ourselves) ----
    const authHeader = req.headers.get('Authorization') ?? ''
    const apikey = req.headers.get('apikey') ?? Deno.env.get('SUPABASE_ANON_KEY') ?? ''
    const supabase = createClient(Deno.env.get('SUPABASE_URL')!, apikey, {
      global: { headers: { Authorization: authHeader } },
      auth: { persistSession: false }
    })
    const { data: userData, error: userErr } = await supabase.auth.getUser()
    if (userErr || !userData?.user) return json({ error: 'not_signed_in' }, 401)
    const userId = userData.user.id

    const body = await req.json().catch(() => ({}))
    const today = /^\d{4}-\d{2}-\d{2}$/.test(body.today ?? '') ? body.today : todayInIndia()

    // ---- Her profile and cycle ----
    const { data: profile } = await supabase.from('profiles').select('*').eq('id', userId).maybeSingle()
    if (!profile?.onboarded_at) return json({ error: 'onboarding_needed' }, 400)

    const loadCycle = async () => {
      const { data: starts } = await supabase.from('cycle_logs').select('log_date')
        .eq('kind', 'period_start').order('log_date', { ascending: false }).limit(13)
      return computeCycle(profile, (starts ?? []).map((s: { log_date: string }) => s.log_date), today)
    }
    let cycle = await loadCycle()

    if (body.action === 'status') return json({ cycle, today })

    const message = String(body.message ?? '').trim().slice(0, 2000)
    if (!message) return json({ error: 'empty_message' }, 400)

    // ---- Recent conversation ----
    const { data: history } = await supabase.from('messages').select('role, content')
      .order('created_at', { ascending: false }).limit(20)
    const past = (history ?? []).reverse()

    await supabase.from('messages').insert({ user_id: userId, role: 'user', content: message })

    // ---- Ask Gemini ----
    const system = buildSystemPrompt(profile, cycle, today)
    let result: HeraResult
    try {
      result = await askGemini(system, past, message)
    } catch (e) {
      const msg = String((e as Error).message)
      const reply = /\b(429|503|500)\b/.test(msg)
        ? "Aw, I'm getting a lot of messages right now 🙈 Give me a minute and try again?"
        : "Sorry, I couldn't think straight just now. Can you send that again?"
      console.error('Gemini error:', msg)
      // `detail` is Google's error text (never contains the key), shown small in the app to help debugging.
      return json({ reply, logged: [], cycle, error: 'ai_unavailable', detail: msg.slice(0, 240) })
    }

    // ---- Save what she told us ----
    const logged = await saveLogs(supabase, userId, profile, result.logs ?? [], today)
    if (logged.some(l => l.kind === 'period_start')) cycle = await loadCycle()

    // ---- She asked to be called something else ----
    const newName = String(result.profile_updates?.name ?? '').replace(/[^\p{L}\p{M}' -]/gu, '').trim().slice(0, 40)
    if (newName && newName !== profile.name) {
      await supabase.from('profiles').update({ name: newName }).eq('id', userId)
    }

    // ---- Safety net: crisis replies always carry the helpline ----
    let reply = (result.reply ?? '').trim() || "I'm here. Tell me more?"
    if ((result.safety_level === 'distress' || result.safety_level === 'danger') && !reply.includes('14416')) {
      reply += `\n\n${HELPLINE}`
    }

    await supabase.from('messages').insert({ user_id: userId, role: 'hera', content: reply })
    return json({ reply, logged, cycle, safety_level: result.safety_level ?? 'none' })
  } catch (e) {
    console.error('hera-chat failed:', e)
    return json({ error: 'server_error' }, 500)
  }
})

// ================= Logging =================

type Log = { kind: string; date: string; value?: string; replace_previous?: boolean }
type HeraResult = { reply: string; logs?: Log[]; safety_level?: string; profile_updates?: { name?: string } }

// deno-lint-ignore no-explicit-any
async function saveLogs(supabase: any, userId: string, profile: any, logs: Log[], today: string) {
  const saved: { kind: string; date: string; value: string | null }[] = []
  for (const log of logs.slice(0, 10)) {
    if (!LOG_KINDS.includes(log.kind)) continue
    if (!/^\d{4}-\d{2}-\d{2}$/.test(log.date ?? '')) continue
    const age = daysBetween(log.date, today)
    if (age < 0 || age > 90) continue // no future dates, nothing older than 3 months
    const value = log.value ? String(log.value).slice(0, 200) : null

    if (log.kind === 'period_start' || log.kind === 'period_end') {
      // One start (or end) per period: a new date within 10 days replaces the old one.
      await supabase.from('cycle_logs').delete().eq('kind', log.kind)
        .gte('log_date', addDays(log.date, -10)).lte('log_date', addDays(log.date, 10))
    }
    const { error } = await supabase.from('cycle_logs')
      .insert({ user_id: userId, log_date: log.date, kind: log.kind, value })
    if (!error) saved.push({ kind: log.kind, date: log.date, value })

    if (log.kind === 'period_start' && !error &&
        (!profile.last_period_start || log.date >= profile.last_period_start || log.replace_previous)) {
      await supabase.from('profiles').update({ last_period_start: log.date }).eq('id', userId)
      profile.last_period_start = log.date
    }
  }
  return saved
}

// ================= Gemini =================

const RESPONSE_SCHEMA = {
  type: 'OBJECT',
  properties: {
    reply: { type: 'STRING', description: "Hera's chat reply to her" },
    logs: {
      type: 'ARRAY',
      items: {
        type: 'OBJECT',
        properties: {
          kind: { type: 'STRING', format: 'enum', enum: LOG_KINDS },
          date: { type: 'STRING', description: 'YYYY-MM-DD' },
          value: { type: 'STRING' },
          replace_previous: { type: 'BOOLEAN' }
        },
        required: ['kind', 'date']
      }
    },
    safety_level: { type: 'STRING', format: 'enum', enum: ['none', 'low_mood', 'distress', 'danger'] },
    profile_updates: {
      type: 'OBJECT',
      properties: { name: { type: 'STRING', description: 'Only if she asks to be called something new' } }
    }
  },
  required: ['reply', 'logs', 'safety_level']
}

// Ask Google which Flash models this key can use, so retired models never break Hera.
let modelCache: { at: number; list: string[] } | null = null
const FALLBACK_MODELS = ['gemini-flash-latest', 'gemini-flash-lite-latest']

async function availableModels(key: string): Promise<string[]> {
  const pinned = Deno.env.get('GEMINI_MODEL')
  if (modelCache && Date.now() - modelCache.at < 6 * 3600_000) {
    return [...new Set([pinned, ...modelCache.list].filter(Boolean))] as string[]
  }
  let list = FALLBACK_MODELS
  try {
    const res = await fetch('https://generativelanguage.googleapis.com/v1beta/models?pageSize=200', {
      headers: { 'x-goog-api-key': key }
    })
    if (res.ok) {
      const data = await res.json()
      const names: string[] = (data.models ?? [])
        .filter((m: { supportedGenerationMethods?: string[] }) => m.supportedGenerationMethods?.includes('generateContent'))
        .map((m: { name: string }) => m.name.replace(/^models\//, ''))
        .filter((n: string) => /flash/.test(n) && !/image|tts|audio|live|embedding|thinking|exp|preview|\d{3}$/.test(n))
      // Newest versions first: 'latest' aliases, then by version number.
      const version = (n: string) => Number((n.match(/gemini-(\d+(?:\.\d+)?)/) ?? [])[1] ?? 0)
      const score = (n: string) => (n.includes('latest') ? 1000 : 0) + version(n) * 10 - (n.includes('lite') ? 1 : 0)
      names.sort((a, b) => score(b) - score(a))
      if (names.length) list = [...new Set([...FALLBACK_MODELS, ...names])].slice(0, 5)
    }
  } catch (e) {
    console.error('Could not list Gemini models:', String(e))
  }
  modelCache = { at: Date.now(), list }
  return [...new Set([pinned, ...list].filter(Boolean))] as string[]
}

async function askGemini(system: string, past: { role: string; content: string }[], message: string): Promise<HeraResult> {
  const key = Deno.env.get('GEMINI_API_KEY')
  if (!key) throw new Error('GEMINI_API_KEY secret is missing')

  // Gemini wants the conversation to start with the user and alternate turns.
  const turns: { role: string; parts: { text: string }[] }[] = []
  for (const m of [...past, { role: 'user', content: message }]) {
    const role = m.role === 'hera' ? 'model' : 'user'
    if (turns.length === 0 && role === 'model') continue
    const last = turns[turns.length - 1]
    if (last && last.role === role) last.parts[0].text += `\n${m.content}`
    else turns.push({ role, parts: [{ text: m.content }] })
  }

  // Free models get busy (503), rate-limited (429) or retired (404): fall through to the next one.
  const models = await availableModels(key)
  let lastError = ''
  for (const model of models) {
    for (const schema of [true, false]) {
      const res = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'x-goog-api-key': key },
        body: JSON.stringify({
          systemInstruction: { parts: [{ text: system }] },
          contents: turns,
          generationConfig: {
            temperature: 0.7,
            maxOutputTokens: 4096,
            responseMimeType: 'application/json',
            // If Google ever rejects the schema, retry once with JSON mode only.
            ...(schema ? { responseSchema: RESPONSE_SCHEMA } : {})
          },
          safetySettings: [
            'HARM_CATEGORY_HARASSMENT', 'HARM_CATEGORY_HATE_SPEECH',
            'HARM_CATEGORY_SEXUALLY_EXPLICIT', 'HARM_CATEGORY_DANGEROUS_CONTENT'
          ].map(category => ({ category, threshold: 'BLOCK_ONLY_HIGH' }))
        })
      })
      if (res.ok) {
        const data = await res.json()
        const text = data?.candidates?.[0]?.content?.parts?.map((p: { text?: string }) => p.text ?? '').join('') ?? ''
        if (!text) {
          lastError = `empty response from ${model} (${data?.candidates?.[0]?.finishReason ?? data?.promptFeedback?.blockReason ?? 'unknown'})`
          break // try the next model
        }
        try {
          return JSON.parse(text)
        } catch {
          return { reply: text, logs: [], safety_level: 'none' }
        }
      }
      lastError = `${res.status} ${model}: ${(await res.text()).slice(0, 200)}`
      console.error('Gemini error:', lastError)
      if (res.status === 400 && schema) continue // retry this model without the schema
      break // 404 (model gone), 429 (limit), 5xx (busy): try the next model
    }
  }
  throw new Error(lastError || 'no model available')
}

// ================= Hera's personality and knowledge =================

const TONES: Record<string, string> = {
  bestie: `Voice: her warm, playful bestie. Use casual words like "babe", "darling", "aw nah", "girl" naturally (not in every sentence). An occasional emoji like 💜 is fine. Sound like a caring friend texting, not a brochure.`,
  gentle: `Voice: warm, calm and kind, like a caring older sister. No pet names, no slang, few emojis.`,
  facts: `Voice: clear, friendly and concise. No pet names, no emojis, no small talk. Lead with the information.`
}

const DIETS: Record<string, string> = {
  vegetarian: 'Vegetarian: no meat, fish or eggs. Dairy is fine.',
  vegan: 'Vegan: no meat, fish, eggs, dairy, ghee, paneer, curd or honey. Use til, ragi, soy, tofu, nuts, seeds, legumes.',
  jain: 'Jain: no meat, fish or eggs, and no root vegetables (onion, garlic, potato, carrot, beetroot, radish, fresh ginger). Dried ginger (sonth) only if she is fine with it. Dairy is fine.',
  eggetarian: 'Eggetarian: vegetarian plus eggs.',
  nonveg: 'Non-vegetarian: all foods, including eggs, fish and chicken.'
}

// deno-lint-ignore no-explicit-any
function buildSystemPrompt(p: any, cycle: any, today: string) {
  const conditions = (p.conditions ?? []).filter((c: string) => c !== 'none')
  return `You are Hera, a chat companion for menstrual cycle and women's health, built for women in India. You are named after the Greek goddess Hera, protector of women. Reply in English.

${TONES[p.tone] ?? TONES.bestie}

## Who you're talking to
- Name: ${p.name || 'not given'}
- Today: ${prettyDate(today)} (${today})
- Life stage: ${p.life_stage}
- Diet: ${DIETS[p.diet] ?? p.diet ?? 'not given'}
- Allergies or foods she avoids: ${p.allergies || 'none given'} (never suggest these)
- Contraception: ${p.contraception || 'none given'}
- Conditions she told you about: ${conditions.length ? conditions.join(', ') : 'none'}
- Cycle: ${describeCycle(cycle)}

## How to reply
- This is a phone chat: keep replies short, usually 2 to 5 sentences. No headings. Bullets only for a short food list.
- When you log something, confirm exactly what you logged, with the date written like "${prettyDate(today)}".
- Ask at most ONE follow-up question per reply, and say optional questions can be skipped.
- Use her name now and then, not every message.
- Be honest about evidence: iron (with vitamin C) during the period, and calcium, magnesium and vitamin B6 for PMS have real evidence. Other phase-based eating is general wellness, so present it as helpful, not essential.

## Logging (the "logs" field)
Log only things she states about HERSELF as facts. Never log from questions, hypotheticals or other people. Resolve relative dates against today: "this morning" or "today" = ${today}, "yesterday" = ${addDays(today, -1)}. If the date is unclear, ask instead of guessing.
- period_start: her period started. value empty. If she corrects a date ("actually it started yesterday"), log period_start with the right date and replace_previous true.
- period_end: her period finished.
- flow: spotting, light, medium or heavy.
- pain: cramps or pain level as a number 0-10 (convert words: mild = 3, bad = 6, severe = 8), plus where if she says.
- mood: one or two words (for example: low, anxious, irritable, happy, lonely).
- energy: low, ok or high.
- symptom: short text (bloating, headache, acne, breast tenderness, nausea, hot flush...).
- sleep: short text (poor sleep, 5 hours...).
- sex_drive: low, normal or high.
- note: anything else health-related she wants remembered.
If there is nothing to log, return an empty list.

## Her name
If she tells you what to call her ("call me Pran", "my name is Pran"), set profile_updates.name to just the name (for example "Pran"), and use it from now on. Otherwise leave profile_updates out.

## Guidance by phase (a 28-day cycle; adjust to hers)
- Menstrual (days 1-5): low energy, cramps. Iron + vitamin C (palak, methi, rajma, chana, dates, jaggery with lemon or amla; eggs, fish or chicken if she eats them). Warm meals like khichdi and dal. Ginger or chamomile tea, a hot water bag. Water about 2.5-3 L, warm fluids. Rest, walks, gentle yoga.
- Follicular (to about day 13): energy and mood rising. Fresh, light food: sprouts, curd, idli, dosa, millets, dals, paneer or tofu. Water about 2-2.5 L. Good time for harder workouts and new plans.
- Ovulatory (around days 14-16): peak energy and confidence, libido often higher. Fibre and antioxidants: cabbage, cauliflower, papaya, fruits, nuts, seeds. Water about 2.5 L.
- Luteal (days 17-28): calm early, then PMS in the last 5-7 days: bloating, cravings, irritability, low or lonely mood. Complex carbs (ragi, jowar, oats, sweet potato), magnesium and B6 (bananas, pumpkin seeds, chickpeas, leafy greens), calcium (dairy, ragi, til). Less salt, sugar and caffeine. Water about 2.5-3 L, which also eases bloating. Remind her gently that low moods here are hormonal and temporary.
Always filter food ideas through her diet and allergies. Prefer everyday Indian meals.

## Special situations
- No natural phases (hormonal contraception): never predict phases, ovulation or fertile windows. Talk about bleeding, symptoms and side effects instead.
- PCOS/PCOD: say predictions are rough. Supportive habits: regular balanced meals with protein and fibre, strength training, good sleep, and regular check-ups.
- Trying to conceive: you can share the estimated fertile window, always as an estimate. Folic acid before conception is recommended (dose is for her doctor). Suggest a fertility check if not pregnant after 12 months of trying, or 6 months if she's 35 or older.
- Fertile windows are NEVER contraception. If she asks about avoiding pregnancy, say app predictions are unreliable for that and suggest talking to a doctor about contraception.
- Pregnancy: no cycle talk. Week-appropriate support, food safety, hydration, rest, what to ask her doctor.
- Perimenopause and menopause: hot flushes, sleep, mood, joint pain, bone health (calcium, vitamin D, protein, strength training). Hormone therapy only as "ask your doctor".
- Sex and sex drive: answer factually and without judgement. Desire naturally changes across the cycle.

## Red flags: always recommend a gynaecologist (without panic)
Period pain that stops daily life or isn't helped by regular painkillers (can signal endometriosis, adenomyosis or fibroids); soaking a pad or tampon every hour for several hours; clots bigger than a ₹5 coin; fainting; fever with pelvic pain; pain during sex; bleeding between periods or after sex; no period for 3 months when not pregnant or menopausal; cycles regularly shorter than 21 or longer than 35 days; any bleeding after menopause.
In pregnancy, bleeding, severe pain, severe headache, blurred vision or reduced baby movement: tell her to contact her doctor or go to hospital now.

## Safety (most important)
Set safety_level:
- "low_mood": sad, low, lonely, stressed. Be warm, link it to her phase if it fits, offer one small comforting idea.
- "distress": hopeless, worthless, "can't go on", overwhelmed with no way out.
- "danger": thoughts of suicide or self-harm, a plan, or immediate danger (including from another person).
For distress or danger: drop all pet names, slang and emojis. Be calm and warm. Thank her for telling you, take it seriously, don't lecture or give pep talks like "you're better than this". Encourage her to reach someone right now, and include: "${HELPLINE}" For danger, ask if she is safe right now.
Otherwise "none".

## Limits
You give guidance, not diagnosis. Never diagnose, never give medicine doses, never promise certainty. Mention seeing a doctor when it matters, not in every message. If asked about unrelated topics, be friendly and brief, then steer back to how she's doing.

Return JSON with "reply", "logs" and "safety_level".`
}
